package deploy

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// GenerateWindowsDeploymentPlan returns a detailed deployment plan for Windows.
func GenerateWindowsDeploymentPlan() string {
	return `{
		"steps": [
			{"action": "create_directory", "path": "%%INSTALL_DIR%%"},
			{"action": "copy_files", "source": "%%BUILD_DIR%%\\guard.exe", "destination": "%%INSTALL_DIR%%\\guard.exe"},
			{"action": "copy_files", "source": "%%BUILD_DIR%%\\guard-ui.exe", "destination": "%%INSTALL_DIR%%\\guard-ui.exe"},
			{"action": "copy_files", "source": "%%BUILD_DIR%%\\openclaw.exe", "destination": "%%INSTALL_DIR%%\\openclaw.exe"},
			{"action": "create_service", "name": "OpenClawGuard", "displayName": "OpenClaw Guard Service", "binaryPath": "%%INSTALL_DIR%%\\guard.exe", "dependencies": ""},
			{"action": "start_service", "name": "OpenClawGuard"}
		]
	}`
}

// CheckWindowsEnvironment verifies that we are running on Windows and that required tools are available.
func CheckWindowsEnvironment() error {
	if runtime.GOOS != "windows" {
		return fmt.Errorf("deploy/windows.go is only supported on Windows, got %s", runtime.GOOS)
	}
	// Check for sc.exe (service control)
	if _, err := exec.LookPath("sc"); err != nil {
		return fmt.Errorf("sc.exe not found in PATH: %w", err)
	}
	return nil
}

// ApplyDeploymentPlan executes the given plan.
// For simplicity, this implementation expects a JSON plan as generated by GenerateWindowsDeploymentPlan
// and performs the steps: create directory, copy files, create and start service.
func ApplyDeploymentPlan(plan string) error {
	// In a real implementation, we would parse the JSON plan.
	// For now, we implement a simplified version that uses environment variables.
	installDir := os.Getenv("INSTALL_DIR")
	if installDir == "" {
		return fmt.Errorf("INSTALL_DIR environment variable not set")
	}
	buildDir := os.Getenv("BUILD_DIR")
	if buildDir == "" {
		// Default to current directory
		buildDir = "."
	}

	// Step 1: Create installation directory
	if err := os.MkdirAll(installDir, 0o755); err != nil {
		return fmt.Errorf("failed to create install directory %s: %w", installDir, err)
	}

	// Step 2: Copy binaries
	filesToCopy := []struct {
		src string
		dst string
	}{
		{filepath.Join(buildDir, "guard.exe"), filepath.Join(installDir, "guard.exe")},
		{filepath.Join(buildDir, "guard-ui.exe"), filepath.Join(installDir, "guard-ui.exe")},
		{filepath.Join(buildDir, "openclaw.exe"), filepath.Join(installDir, "openclaw.exe")},
	}

	for _, f := range filesToCopy {
		if _, err := os.Stat(f.src); err != nil {
			return fmt.Errorf("source file not found: %s (%w)", f.src, err)
		}
		if err := copyFile(f.src, f.dst); err != nil {
			return fmt.Errorf("failed to copy %s to %s: %w", f.src, f.dst, err)
		}
	}

	// Step 3: Create Windows service
	serviceName := "OpenClawGuard"
	binaryPath := filepath.Join(installDir, "guard.exe")
	// Use sc.exe to create service
	// sc create <serviceName> binPath= "<binaryPath>" start= auto
	out, err := exec.Command("sc", "create", serviceName, "binPath= "+quote(binaryPath), "start= auto").CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to create service %s: %w, output: %s", serviceName, err, string(out))
	}

	// Step 4: Start service
	out, err = exec.Command("sc", "start", serviceName).CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to start service %s: %w, output: %s", serviceName, err, string(out))
	}

	return nil
}

// copyFile copies a file from src to dst.
func copyFile(src, dst string) error {
	source, err := os.Open(src)
	if err != nil {
		return err
	}
	defer source.Close()

	destination, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer destination.Close()

	_, err = io.Copy(destination, source)
	if err != nil {
		return err
	}
	// Flush to ensure write completes
	if err := destination.Sync(); err != nil {
		return err
	}
	return nil
}

// quote wraps a string in quotes for Windows command line if it contains spaces.
func quote(s string) string {
	if strings.Contains(s, " ") {
		return `"` + s + `"`
	}
	return s
}
